### ISSUE TITLE
Anonymous Posting - Testing & Documentation

### ISSUE THREAD

**Issue by runxinz** [CMU-313/spring24-nodebb-wildcats#17]
**User Story:** As a student, I want to make a post anonymously, so that I can ask a question without revealing my identity.

**Estimated effort:** 10 Hours

**Dependencies:** Might need to wait for issue #16 to be solved

**Initial assignments:** @wenchaohu1 @aqimeral @22zhuamanda 

**Milestones:** Complete by the second week of Sprint 2 if dependencies are achieved.

**Acceptance criteria:**
Write automated tests that check for:
1. Posts can become 'anonymous' after the isAnonymous value is set to true
2. Posts have default setting of not anonymous - isAnonymous value defaults to false.

**Comment by FireACNC** [comment]
Solved by #20
